# Generated by Django 5.0 on 2024-12-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0006_logs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информация'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Заголовки Меню', 'verbose_name_plural': 'Заголовки Меню'},
        ),
        migrations.AlterModelOptions(
            name='rules',
            options={'verbose_name': 'Правила игры', 'verbose_name_plural': 'Правила игры'},
        ),
        migrations.AddField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
